# Generated by Django 5.1.5 on 2025-03-03 11:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('caddress', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('ccontact', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('cemail', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='inscategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insname', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='insurancecomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insname', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='motorncb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncbno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='motorpolcoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polname', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='motorpoltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pltname', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='policycopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/policycopy/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rccopymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/rccopy/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='suminstype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='confirmed_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revert', models.BooleanField(default=False)),
                ('relegate', models.BooleanField(default=False)),
                ('vid', models.CharField(max_length=20, unique=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_type', models.CharField(blank=True, max_length=255, null=True)),
                ('renewal_days', models.IntegerField(default=30)),
                ('renewal_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedOrderFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(default='', help_text='Name associated with the follow-up', max_length=20)),
                ('fodate', models.DateField(help_text='Date of the follow-up')),
                ('fotime', models.TimeField(help_text='Time of the follow-up')),
                ('entrydate', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp for when this entry was created or modified')),
                ('confirmed_order', models.ForeignKey(help_text='The confirmed order associated with this follow-up', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.confirmed_enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='', max_length=30)),
                ('customername', models.CharField(default='', max_length=20)),
                ('refrence', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('1', 'HOT'), ('2', 'WARM'), ('3', 'COLD')], default='', max_length=20)),
                ('subproduct', models.CharField(blank=True, default='', max_length=20)),
                ('closuredate', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='', max_length=100)),
                ('flag', models.TextField(blank=True, default='', max_length=200)),
                ('enqtype', models.CharField(blank=True, default='', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_lost', models.BooleanField(default=False)),
                ('is_reverted', models.BooleanField(default=False)),
                ('is_relegated', models.BooleanField(default=False)),
                ('lostdate', models.DateField(blank=True, null=True)),
                ('lost_renewal_days', models.IntegerField(default=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.executive')),
                ('files', models.ManyToManyField(blank=True, to='Riva.fileuploadmodel')),
                ('products', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.products')),
            ],
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry'),
        ),
        migrations.CreateModel(
            name='firepol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expolno', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('asstval', models.FloatField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(max_length=255)),
                ('fodate', models.DateField()),
                ('fotime', models.TimeField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.enquiry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='insurancebranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insbranch', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('branch_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('inscomp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.insurancecomp')),
            ],
        ),
        migrations.CreateModel(
            name='marinepol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expolno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('lrno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('consignmentval', models.FloatField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
            ],
        ),
        migrations.CreateModel(
            name='personal_Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dateof_reg', models.DateField(default=datetime.date.today)),
                ('pincode', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('aadhar', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('pan_card', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('nominee_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('relationship', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('nominee_age', models.IntegerField(blank=True, null=True)),
                ('amount_insured', models.FloatField()),
                ('premium', models.FloatField()),
                ('total_gst', models.FloatField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('renewals', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.inscategory')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
                ('ins_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.insurancebranch')),
                ('inscomp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.insurancecomp')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personal_accident_FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(max_length=255)),
                ('fodate', models.DateField()),
                ('fotime', models.TimeField()),
                ('personal_Acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.personal_accident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('baseamount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('boq', models.FileField(blank=True, null=True, upload_to='boqs/')),
                ('finalamount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_closing_date', models.DateField()),
                ('workorder', models.FileField(blank=True, null=True, upload_to='workorders/')),
                ('boq', models.FileField(blank=True, null=True, upload_to='boqs/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='motorpol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expolno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('engineno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('chassisno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dor', models.DateField(default=datetime.date.today)),
                ('regno', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rtocity', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('makemodel', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('idv', models.FloatField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
                ('ncb', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.motorncb')),
                ('tpname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.insurancecomp')),
                ('polcov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.motorpolcoverage')),
                ('poltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.motorpoltype')),
                ('rccopy', models.ManyToManyField(blank=True, related_name='motorpols', to='Riva.rccopymodel')),
            ],
        ),
        migrations.CreateModel(
            name='retailpolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strtdate', models.DateField(default=datetime.date.today)),
                ('enddate', models.DateField(default=datetime.date.today)),
                ('amtpd', models.FloatField(default=0)),
                ('amtpdgst', models.FloatField(default=0)),
                ('polno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rtcreated_at', models.DateField(auto_now_add=True)),
                ('renewals', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
                ('insbranch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.insurancebranch')),
                ('inscomp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.insurancecomp')),
                ('newpolcopy', models.ManyToManyField(blank=True, related_name='policycopy', to='Riva.policycopy')),
                ('retpol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.inscategory')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vid', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.personal_accident')),
                ('retail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.retailpolicies')),
            ],
        ),
        migrations.CreateModel(
            name='retailpolicies_FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.CharField(max_length=255)),
                ('fodate', models.DateField()),
                ('fotime', models.TimeField()),
                ('retail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Riva.retailpolicies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevertRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revert_remarks', to='Riva.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='shopkeeperspol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expolno', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stkval', models.FloatField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
            ],
        ),
        migrations.CreateModel(
            name='mediclaimpol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expolno', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('suminsured', models.FloatField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
                ('sitype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.suminstype')),
            ],
        ),
        migrations.CreateModel(
            name='wcpol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expolno', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('empcount', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.FloatField(default=0)),
                ('placeofwork', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('naturework', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.clients')),
            ],
        ),
    ]
