# Generated by Django 5.1.5 on 2025-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='Gst_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='premium_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='sum_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
