# Generated by Django 5.1.5 on 2025-03-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0002_confirmed_enquiry_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='files',
            field=models.ManyToManyField(blank=True, to='Riva.fileuploadmodel'),
        ),
    ]
