# Generated by Django 5.1.5 on 2025-03-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0003_confirmed_enquiry_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.TextField()),
                ('fodate', models.DateField()),
                ('fotime', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry')),
            ],
        ),
    ]
