# Generated by Django 5.1.5 on 2025-03-07 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0004_followup_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup_history',
            name='confirmed_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.confirmed_enquiry'),
        ),
        migrations.AlterField(
            model_name='followup_history',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry'),
        ),
    ]
