# Generated by Django 5.1.5 on 2025-03-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0005_followup_history_confirmed_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_FollowUp_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foname', models.TextField()),
                ('fodate', models.DateField()),
                ('fotime', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.personal_accident')),
                ('Retail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Riva.retailpolicies')),
            ],
        ),
    ]
