# Generated by Django 5.1.5 on 2025-03-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0006_retail_followup_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='client_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='tpa_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='tpa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='tpa_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='vrd_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='vrd_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='vrd_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
