# Generated by Django 5.1.5 on 2025-03-12 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0007_confirmed_enquiry_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_accident',
            name='amount_insured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_accident',
            name='dateof_reg',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='personal_accident',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='personal_accident',
            name='premium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_accident',
            name='total_gst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
