# Generated by Django 5.1.5 on 2025-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0008_alter_personal_accident_amount_insured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_enquiry',
            name='cal_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
