# Generated by Django 5.1.5 on 2025-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0009_confirmed_enquiry_cal_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_accident',
            name='p_gst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
