# Generated by Django 5.1.5 on 2025-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0010_personal_accident_p_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailpolicies',
            name='gstval',
            field=models.FloatField(default=0),
        ),
    ]
