# Generated by Django 5.1.5 on 2025-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0011_retailpolicies_gstval'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailpolicies',
            name='amount_insured',
            field=models.FloatField(default=0),
        ),
    ]
