# Generated by Django 5.1.3 on 2024-12-31 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_target_status_remove_target_target_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
