# Generated by Django 5.1.3 on 2025-01-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='functionBlockData',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=40, unique=True)),
                ('block_type', models.CharField(max_length=40)),
                ('mode', models.CharField(max_length=40)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_connections', to='fluidsim.functionblockdata')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='fluidsim.functionblockdata')),
            ],
        ),
        migrations.AddField(
            model_name='functionblockdata',
            name='true_LB_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks'),
        ),
        migrations.CreateModel(
            name='LogicBlocksDesignParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_block_design', to='fluidsim.logicblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlocksLifingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlocksPerformanceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlocksPrognosticParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
        migrations.AddField(
            model_name='logicblocks',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.modules'),
        ),
        migrations.CreateModel(
            name='SubModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='fluidsim.modules')),
            ],
        ),
        migrations.AddField(
            model_name='logicblocks',
            name='submodule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_blocks', to='fluidsim.submodules'),
        ),
    ]
