# Generated by Django 5.1.3 on 2025-01-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidsim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='NO NAME')),
                ('network_type', models.TextField(default='NONE')),
            ],
        ),
        migrations.AddField(
            model_name='functionblockdata',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluidsim.network'),
        ),
    ]
