# Generated by Django 5.1.3 on 2025-01-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidsim', '0002_network_functionblockdata_network_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluidsim.network'),
        ),
    ]
