# Generated by Django 5.1.3 on 2025-01-23 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidsim', '0003_connections_network_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicBlockDesignOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlockLifingOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlockPerformanceOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LogicBlockPrognosticOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_param_name', models.CharField(default='NONE', max_length=30)),
                ('unit', models.CharField(default='NONE', max_length=30)),
                ('LB_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluidsim.logicblocks')),
            ],
        ),
    ]
