# Generated by Django 5.1.3 on 2025-01-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidsim', '0004_logicblockdesignoutputs_logicblocklifingoutputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionblockdata',
            name='proxy_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
