# Generated by Django 5.1.3 on 2025-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidsim', '0005_functionblockdata_proxy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionblockdata',
            name='proxy_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
