# Generated by Django 5.1.3 on 2025-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidsim', '0006_alter_functionblockdata_proxy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicblockdesignoutputs',
            name='out_param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockdesignoutputs',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocklifingoutputs',
            name='out_param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocklifingoutputs',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockperformanceoutputs',
            name='out_param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockperformanceoutputs',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockprognosticoutputs',
            name='out_param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockprognosticoutputs',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocksdesignparams',
            name='param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocksdesignparams',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockslifingparams',
            name='param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblockslifingparams',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocksperformanceparams',
            name='param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocksperformanceparams',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocksprognosticparams',
            name='param_name',
            field=models.CharField(default='NONE', max_length=130),
        ),
        migrations.AlterField(
            model_name='logicblocksprognosticparams',
            name='unit',
            field=models.CharField(default='NONE', max_length=130),
        ),
    ]
