# Generated by Django 5.1.3 on 2025-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0043_alter_enquiry_enqtype_alter_enquiry_refrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hidrec_wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=5000)),
                ('hidrec_wash_text', models.CharField(max_length=5000)),
                ('carwash_text', models.CharField(max_length=5000)),
                ('specification', models.CharField(max_length=10000)),
                ('terms_conditions', models.CharField(max_length=10000)),
                ('general_maintenance', models.CharField(max_length=10000)),
            ],
        ),
    ]
