# Generated by Django 5.1.3 on 2025-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0044_hidrec_wash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidrec_wash',
            name='carwash_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hidrec_wash',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hidrec_wash',
            name='general_maintenance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hidrec_wash',
            name='hidrec_wash_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hidrec_wash',
            name='qno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hidrec_wash',
            name='specification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hidrec_wash',
            name='terms_conditions',
            field=models.TextField(),
        ),
    ]
