# Generated by Django 5.1.3 on 2025-02-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0046_hidrec_wash_price_hidrec_wash_priceoil_skimmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidrec_wash',
            name='enquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Riva.enquiry'),
            preserve_default=False,
        ),
    ]
