# Generated by Django 5.1.3 on 2025-02-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0047_hidrec_wash_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidrec_wash',
            name='enquiry',
        ),
    ]
