# Generated by Django 5.1.3 on 2025-02-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0048_remove_hidrec_wash_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidrec_wash',
            name='qno',
        ),
    ]
