# Generated by Django 5.1.3 on 2025-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0049_remove_hidrec_wash_qno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedHidrecWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contents', models.TextField()),
                ('hidrec_wash_text', models.TextField()),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('carwash_text', models.TextField()),
                ('priceoil_skimmer', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.TextField()),
                ('terms_conditions', models.TextField()),
                ('general_maintenance', models.TextField()),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
