# Generated by Django 5.1.3 on 2025-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riva', '0050_confirmedhidrecwash'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedhidrecwash',
            name='enquiry_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
